name: Blog posts on ReadMe
on:
  schedule:
    # Runs every day at 9am UTC
    - cron: '0 1 * * *'

jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://musing.vercel.app/feed.xml
          count: 10
      - name: Commit file changes
        run: |
            git config --global user.name 'Parth'
            git config --global user.email 'desaiparth2000@gmail.com'
            git add .
            git diff --quiet --cached || git commit -m "Update README" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
