name: Generate Blog List
on:
  push:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Readme Blog Post Action
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: "https://musing.vercel.app/feed.xml"
          max_posts_per_url: 5
          position_indicator: "post-list"
          locale: "en-US"
          time_zone: "America/Denver"
          output_dir: "generated_files"
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated content
          skip_checkout: true
